### PR TITLE
Convert project to Godot 4

### PR DESCRIPTION
**Pull request by scharissis**
Started with Godot's auto-import (on Godot 4.1.3), then added some manual fixes. After the fixes, it runs on my Windows 11 machine with no errors/debug output.

image

### CODE REVIEW

**Comment by ParadoxV5** [comment]
From #8’s (lack of) activity, I suspect that this project is abandoned without notice.

**Comment by scharissis** [comment]
I agree that it seems that way. But I had to try :)

**Comment by AThousandShips** [comment]
The project has been fully integrated into the [demo projects](https://github.com/godotengine/godot-demo-projects) and is maintained there now

**Comment by ParadoxV5** [comment]
> The project has been fully integrated into the [demo projects](https://github.com/godotengine/godot-demo-projects) and is maintained there now

I see – godotengine/godot-demo-projects#884

Request to archive this repository and update its status on the README and [in the tutorial](https://docs.godotengine.org/en/stable/getting_started/first_3d_game/01.game_setup.html#setting-up-the-game-area)

**Comment by akien-mga** [comment]
Thanks for the contribution! This project is archived and replaced by https://github.com/godotengine/godot-demo-projects/tree/master/3d/squash_the_creeps, please contribute there instead!

**Pull request closed without merging**
